export const users = [
	{
		name: 'Ansley',
		avatar: 'https://i.pravatar.cc/50/50?id=1',
		id: 1,
	},
	{
		name: 'Genesis',
		avatar: 'https://i.pravatar.cc/50/50?id=2',
		id: 2,
	},
	{
		name: 'Yazmin',
		avatar: 'https://i.pravatar.cc/50/50?id=3',
		id: 3,
	},
	{
		name: 'Vito',
		avatar: 'https://i.pravatar.cc/50/50?id=4',
		id: 4,
	},
	{
		name: 'Enos',
		avatar: 'https://i.pravatar.cc/50/50?id=5',
		id: 5,
	},
	{
		name: 'Jordyn',
		avatar: 'https://i.pravatar.cc/50/50?id=6',
		id: 6,
	},
	{
		name: 'Eddie',
		avatar: 'https://i.pravatar.cc/50/50?id=7',
		id: 7,
	},
	{
		name: 'Dallas',
		avatar: 'https://i.pravatar.cc/50/50?id=8',
		id: 8,
	},
	{
		name: 'Daphnee',
		avatar: 'https://i.pravatar.cc/50/50?id=9',
		id: 9,
	},
	{
		name: 'Lempi',
		avatar: 'https://i.pravatar.cc/50/50?id=10',
		id: 10,
	},
]

export const messages = [
	'Tempore officiis velit. Necessitatibus nostrum et rerum qui. Aspernatur non qui voluptatem magni quas. Molestias fugiat sapiente.',
	'Rerum quia sit blanditiis. Et quam in fugit quia rerum sed. Officia quisquam facilis pariatur nemo sint corrupti qui. Sit nobis et voluptatem aspernatur sit. Iste molestiae sed in aliquam voluptatem omnis rem neque provident.',
	'Eligendi non sunt aut. Vel eos nam et est amet. Dicta dolores et minus omnis ipsam. Facilis qui laudantium temporibus quam nisi laboriosam laboriosam quia eligendi. Libero voluptas incidunt placeat ab laboriosam reiciendis suscipit.',
	'Iure optio iure aspernatur animi non sit est et. Amet nobis voluptatem laboriosam necessitatibus est ut. Rerum et sequi aut illo rerum autem temporibus quia. Illum ut qui eum enim est enim.',
	'Accusamus sed eaque voluptas. Quia rerum nihil sunt. Quae voluptatem reprehenderit perspiciatis.',
	'Occaecati praesentium dolorum dignissimos.',
	'Nam itaque aspernatur. Qui in dolorum impedit fugit omnis optio.',
	'Dolorum et enim rerum recusandae rerum.',
	'Est odio magnam molestiae nulla velit consectetur.',
	'Consequuntur et sunt iusto.',
	'Consequuntur fugiat a tempora enim.',
	'Maxime qui perferendis.',
	'Illum cum quam neque quia. Saepe minus quaerat qui rerum sit.',
	'Possimus at quas sint. Maxime et nihil et at delectus autem eos. Voluptatibus veniam nemo voluptates praesentium vel. Dolorem ullam omnis hic sint rerum ratione. Qui minus cupiditate reiciendis at molestiae voluptatum.',
	'Tempore accusantium voluptas adipisci alias magnam similique quia dolore. Illum eum modi. Sit aut quidem aut. Dolores dolore quisquam accusamus qui delectus architecto saepe.',
	'Temporibus quia nihil quasi. Omnis illo aut.',
	'Quia vitae quasi sint ad ut aut. Et et qui delectus ullam esse sint maxime.',
	'Maiores sit modi vel et ipsum aliquam odit omnis corrupti. Omnis recusandae omnis et iste corporis fugit cumque. Iure iste quibusdam. Illo modi vel perferendis nihil qui consequatur aliquam. Nesciunt saepe voluptatem distinctio incidunt.',
	'Quia voluptas fugit consequatur porro.',
	'Doloribus doloribus et numquam vel quo ratione perferendis. Ut et voluptatum ipsum possimus vitae sed nemo explicabo id. Perferendis deleniti tempore quaerat. Eius exercitationem non molestiae possimus. Nostrum qui natus eos placeat voluptas rem dolore corporis ea.',
	'Quae est quas amet. Ab odit voluptas nemo voluptatibus ullam et quo. Excepturi enim rerum animi dolorem harum nemo fugiat. Officiis dolorem inventore.',
	'Ea quasi quia quod dolorum quasi inventore culpa delectus.',
	'Commodi qui neque aut id culpa reiciendis tenetur ex. Eos maiores aut aut et eligendi repellendus dolorem. Ut sint enim laborum tempora consequatur in. Ut distinctio nobis id. Ratione eius animi maiores totam qui necessitatibus.',
	'Ullam minima dolor sint. Officiis qui quo dolor tempora. Eos veniam qui consequatur.',
	'Veniam unde sunt aut. Corrupti vel atque blanditiis laboriosam sunt minima omnis. Animi delectus doloremque sed. Est temporibus corrupti tempore est quo sapiente nam atque. Quasi quia tempore.',
	'Molestias est expedita quis et. Accusantium qui occaecati. Aut occaecati inventore vel aut perferendis tenetur assumenda alias. Reprehenderit accusamus numquam.',
	'Perferendis culpa nam.',
	'Nisi eius minima ipsa illo.',
	'In tenetur sunt.',
	'Repellat ut et itaque aut sit impedit itaque ut provident. Sed reprehenderit explicabo placeat tempore ut et quidem omnis.',
	'Quia qui aut.',
	'Dolorem ipsa sequi veniam molestiae neque similique reprehenderit magnam. Sequi iure provident.',
	'Dolorum inventore aliquam reiciendis aut sit et. Sit eius beatae deleniti commodi tempora recusandae nihil temporibus deleniti. Explicabo et dolores sed quo aut id aliquid. Et sed alias. Totam qui sit.',
	'Dolor veritatis adipisci atque qui et. Doloremque porro minus omnis cupiditate cum ut molestiae est.',
	'Impedit molestiae eos harum et doloremque consequuntur sed hic.',
	'Est repellendus eius sed tenetur unde quo. Unde eos occaecati veniam consequuntur odit quia et quos dolorem. Minima sunt quis et voluptas voluptatem totam ad.',
	'Voluptas consectetur quas incidunt dicta ea dolorem et nisi autem. Eum minima adipisci quos excepturi. Cumque fugit perferendis repellat.',
	'Et voluptatem non dolor officiis. Distinctio eligendi delectus.',
	'Sit commodi doloremque enim corrupti quo. Impedit dolores dolor. Nostrum et assumenda recusandae dolor quasi qui laudantium. Eos illum voluptate consequuntur voluptatum sit numquam officiis.',
	'Et quam explicabo aut accusantium et id quas. Totam sit maiores asperiores non. Laborum reprehenderit dolorem vel nulla placeat quisquam consectetur exercitationem sit. Aliquid ipsum dolores ut porro magni. Harum cumque voluptatem eveniet et facilis.',
	'Nihil ducimus voluptas ut eum.',
	'Assumenda alias vel omnis ut id aliquam eveniet. Voluptas et est dolores placeat eos voluptatem soluta a adipisci.',
	'Aut aliquid exercitationem maiores exercitationem voluptatem. Quasi minima laudantium vero consequatur.',
	'Maxime quam eum facilis nobis vel. Voluptatem numquam non iste sed et sequi.',
	'Pariatur ipsum non architecto similique voluptatem dolor molestiae suscipit. Velit at sint tempore. Ipsa maiores ab dolore et sit in in. Veritatis eligendi necessitatibus autem quia. Facilis ut sit expedita aut tenetur dolores mollitia sit.',
	'Velit eveniet delectus porro maxime. Sunt illum dolorum velit.',
	'Laboriosam animi omnis officia dolores. Quia qui deserunt facilis itaque aut corporis quasi. Voluptatibus omnis consequatur consequatur.',
	'Similique consequuntur consequatur nihil laudantium placeat. Tempora mollitia aut odio vero sed. Vero qui in maxime dolores eveniet eum minus vel. Perferendis est quia dolores vitae distinctio.',
	'Commodi molestiae nihil veritatis mollitia qui rerum. Laborum omnis aut ea recusandae. Est voluptas nihil repellendus similique eum tenetur. Impedit in voluptatem qui aut sunt.',
	'Ea natus officiis et cumque iure aut aut.',
	'Aut quia error fugiat. Molestiae dolorem ut earum ad. Consequatur suscipit sequi nemo nostrum provident fuga aut consequatur. Eius possimus voluptas.',
	'Saepe quis ut commodi et. Quis dolor repudiandae et est autem explicabo deleniti odio.',
	'Et facilis dolore eveniet ut amet molestias. Modi numquam ab nostrum eveniet. Ad molestiae praesentium. Necessitatibus deleniti accusantium. Assumenda temporibus quas.',
	'A neque eveniet saepe. Necessitatibus est similique consequatur. Molestiae sit officiis quidem. Laboriosam quisquam quo.',
	'Minus aut pariatur. Est molestiae eligendi tenetur repudiandae autem beatae laudantium saepe. Et soluta asperiores.',
	'Praesentium dolorem dolor ex quidem. Facere dignissimos est dolor. Voluptatum laudantium voluptatem iste vitae. Consequatur voluptatum possimus.',
	'Laborum occaecati quis sapiente hic ad est libero. Reprehenderit omnis ab excepturi odio mollitia aut qui. Eligendi nihil eum voluptatem delectus beatae quia laboriosam id omnis.',
	'Eveniet nesciunt aut laboriosam similique quasi omnis officia tempore beatae.',
	'Tempora molestiae sit quibusdam. Quo quis quo quia natus iure ipsam.',
	'Quisquam voluptate dolores et ipsam ullam libero quisquam.',
	'Quisquam eaque est illum. Quis velit est in nostrum voluptatem nesciunt voluptate esse. Qui ullam distinctio nisi.',
	'Numquam alias reprehenderit dolorem laborum. Exercitationem et numquam laboriosam. Similique inventore voluptatem perferendis omnis ex et facere.',
	'Ut aut rerum non quidem nesciunt dolorem. Qui aut consequatur repellendus porro eaque et.',
	'Ullam qui omnis natus vero error qui in. Voluptatum nihil illum architecto in consectetur.',
	'Animi ut commodi omnis ex. Est placeat qui atque eius aut rerum placeat harum voluptas.',
	'Neque itaque blanditiis illo aperiam reprehenderit similique. Nostrum ipsum officiis voluptatem officiis. Amet deleniti nihil vitae.',
	'Dolorem non alias nobis. Occaecati blanditiis et laboriosam ut itaque nihil repudiandae voluptas.',
	'Est ipsa voluptate veritatis neque excepturi.',
	'Accusamus enim velit vero quia et doloribus sapiente. Odit in reprehenderit et. Asperiores sit excepturi qui sed quo sequi libero. Sequi est incidunt perferendis.',
	'Aut incidunt cupiditate. Ut maxime itaque labore dolor perferendis voluptatem est. Autem id quasi provident et modi dignissimos error aut corporis.',
	'Numquam sed consequatur nesciunt.',
	'Quis libero eligendi voluptate accusamus aspernatur iusto explicabo ut possimus.',
	'Neque voluptatem corporis error.',
	'Molestiae quos modi aut provident nesciunt eum aliquid cumque.',
	'Facilis aut quas. Alias voluptate adipisci culpa. Asperiores tempore aut provident quisquam voluptates. Et iure non ipsa omnis quo voluptas rerum. Enim veritatis omnis ut perspiciatis.',
	'Cum laudantium voluptas minima quia ducimus eum autem sit. Aut perferendis tempore beatae autem ex molestias molestiae dolore vel. Quia rerum molestiae. Cupiditate voluptas perferendis quae qui. Officiis eos consectetur.',
	'Eveniet sed corporis nemo aperiam. Sed quae nostrum labore nisi nam. Dignissimos quia sequi.',
	'Ipsum commodi perspiciatis nostrum perspiciatis voluptatem et.',
	'Quas ipsam asperiores autem est assumenda dolor qui officiis.',
	'Voluptas in praesentium.',
	'Doloremque et placeat non suscipit exercitationem sunt debitis rerum eligendi. Ut aperiam aperiam sit quis ut deleniti fugit qui. Et aut sunt ea in optio placeat sit repellat eos. Ut alias pariatur minima quia. Impedit reprehenderit doloribus qui cupiditate aliquid.',
	'Omnis quas voluptas eum sit et odit culpa voluptate dolores. Ipsa perferendis et. Et blanditiis enim repellendus voluptas provident eos. Officiis voluptas veniam nihil.',
	'Fugiat maxime possimus. Cum esse impedit ad et. Et voluptates aperiam. Et et aut molestiae distinctio modi eveniet culpa. Voluptas facilis quam ut enim perferendis dolor omnis amet amet.',
	'Nihil ea neque. Enim dicta hic voluptatum.',
	'Qui rem excepturi laborum dolorem numquam odit. Laborum nihil fugiat modi suscipit voluptatem aut laborum. Nulla maiores ut ab culpa qui ex non id qui.',
	'Et omnis explicabo numquam enim molestiae ullam. Quod nihil velit itaque aut commodi quaerat eaque architecto. Maiores libero illum odit voluptates numquam id cumque facere consequatur. Nesciunt odit eaque eum consequuntur doloribus quaerat.',
	'Ab minus quod voluptatem et nisi quod quibusdam facere. Voluptates unde sapiente nobis esse. Deserunt perspiciatis delectus. Fuga dolores magni error ab sit qui. Quas explicabo rerum ullam veniam mollitia ut ut voluptatum qui.',
	'Voluptas voluptatem nemo distinctio ut id nihil in ut ea. Commodi qui mollitia iure qui et.',
	'Debitis illo quas. Quis est et. Aut eius quo ut nemo voluptatibus ratione ullam. Ut soluta sunt et ea quis molestiae est rerum doloribus.',
	'Magnam illum quae aut doloribus. Quis qui ratione et enim perspiciatis. Nulla similique voluptates vel facilis dolor molestiae placeat itaque amet. Minima nihil omnis.',
	'Quam architecto ab et minima tempora non atque perspiciatis.',
	'Labore quo nesciunt ad qui fuga in atque perferendis. Molestiae provident atque. Dolorem sequi sint exercitationem dolor natus amet aliquam. Quos deleniti occaecati cupiditate placeat tenetur delectus.',
	'Nisi expedita tempora molestias est incidunt. Sit qui et est.',
	'Aliquid iste minus suscipit aut et.',
	'Omnis commodi nemo rerum dolores ullam beatae asperiores quod rem. Eligendi libero fugit tempora animi velit accusantium molestiae et. Et magnam aut aliquid consequatur totam. Odio nesciunt quasi iure pariatur.',
	'Cumque doloribus consequuntur quae quam dolores voluptatibus. Nihil nihil sunt non. Aliquid neque incidunt hic consequatur pariatur aut. Dolores voluptatibus fuga perferendis praesentium. Fuga sunt et qui qui magnam sint ut.',
	'Vel nemo aliquid velit ad tempore eaque exercitationem. Eos ut deleniti iusto quis qui quis nihil. Qui sint veniam ratione perferendis quos temporibus ex id. Dolore aut fugit facilis.',
	'Mollitia fugiat dolore aspernatur aut dolorem optio at. Aspernatur facere nam mollitia nam dolor.',
	'Vel repudiandae corrupti aut ratione aut corrupti consequuntur. Voluptas atque qui quia provident consectetur aut excepturi.',
	'Ratione fuga eum et omnis ea velit repellendus sit expedita. Dolorem officia quis alias fugit quia et porro eos. Nemo explicabo accusantium totam voluptatem quae libero aspernatur. Eos dolorum qui reprehenderit ut. Sed rerum qui cumque aut.',
]
